### ISSUE TITLE
Support for multiple backup structures

### ISSUE THREAD

**Issue by deeagle** [deeagle/rob#5]
File: `config.yml`

```yml
- backups:
  - one
    - keep_files: 10
    - keep_path: /tmp/rob-test-files
    - keep_file_prefix: db-backup
  - two
    - keep_files: 5
    - keep_path: /tmp/rob-test-files2
    - keep_file_prefix: db-backuper
```
